# @package _global_
training:
  task_name: AllegroInhandRotationSac
  sim_backend: mujoco
algo:
  num_envs: 2048
  batch_size: 16384
  replay_buffer_n: 1024
  gamma: 0.99
  tau: 0.005
  actor_lr: 1.0e-4
  save_interval: 1000
  max_iterations: 25000
  algo_params:
    alpha_init: 0.001
    target_entropy_ratio: 0.0
    max_grad_norm: 1.0
reward:
  scales:
    rotate: 0.0
    alive: 10.0
    obj_linvel: -0.0
    pose_diff: -0.0
    torque: -0.0
    work: -0.0
    drop: -4000.0
  angvel_clip_min: -0.5
  angvel_clip_max: 0.5
  reset_z_threshold: 0.125
