# @package _global_
training:
  task_name: G1JoystickRough
  sim_backend: motrix
algo:
  num_envs: 2048
  num_steps_per_env: 24
  max_iterations: 2000
  empirical_normalization: true
  obs_groups:
    actor:
      - policy
    critic:
      - critic
  policy:
    init_noise_std: 0.8
  algorithm:
    learning_rate: 1.0e-3
    entropy_coef: 5.0e-3

env:
  render_offset_mode: zero
  domain_rand:
    randomize_kp: false
    randomize_kd: false
  control_config:
    action_scale: 0.5
  commands:
    vel_limit:
      - [0.0, 0.0, -1.0]
      - [1.0, 0.0, 1.0]
    resampling_time: 10.0
    heading_command: false
    heading_range: [-3.141592653589793, 3.141592653589793]
  gait_phase_init_mode: offset_phase
  reset_base_qvel_limit: 0.05
  curriculum:
    enabled: false
  noise_config:
    level: 1.0
    scale_joint_angle: 0.01
    scale_joint_vel: 1.5
    scale_gyro: 0.2
  scene:
    model_file: src/unilab/assets/robots/g1/g1.xml
    fragment_files:
      - src/unilab/assets/robots/g1/locomotion_task.xml
    terrain:
      hfield_name: terrain_hfield
      geom_name: floor
      generator:
        seed: 42
        curriculum: false
        size: [8.0, 8.0]
        num_rows: 6
        num_cols: 6
        border_width: 1.0
  terrain_scan:
    enabled: true
    geom_name: floor
  termination_config:
    terrain_out_of_bounds: true
    terrain_distance_buffer: 3.0
reward:
  scales:
    track_lin_vel_xy_yaw_frame_exp: 1.0
    track_ang_vel_z_world_exp: 2.0
    feet_air_time: 0.25
    feet_slide: -0.1
    dof_pos_limits_ankle: -1.0
    joint_deviation_hip: -0.1
    joint_deviation_arms: -0.1
    joint_deviation_torso: -0.1
    lin_vel_z: -2.0
    ang_vel_xy: -0.05
    flat_orientation_l2: -1.0
    action_rate_l2: -0.005
    dof_torques_l2: -1.5e-7
    dof_acc_l2: -1.25e-7
    alive: 1.0
  tracking_sigma: 0.5
  gait_frequency: 1.5
  feet_phase_swing_height: 0.09
  feet_phase_tracking_sigma: 0.008
  base_height_target: 0.765
  min_forward_speed_for_gait_reward: 0.05
  min_base_height: 0.5
  max_tilt_deg: 35.0
  feet_air_time_threshold: 0.4
  feet_air_time_command_threshold: 0.1
